version: '3.8'
services:
  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    environment:
      - SERVER_PORT=5000
    volumes:
      - ./api-gateway:/app
    command: yarn server:watch

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: